### ISSUE TITLE
Bug Report: Extract BAD ZIp File

### ISSUE THREAD

**Issue by NeuHix** [Foldex/AdwSteamGtk#10]
**This issue is specific to AdwSteamGtk and not the upstream project:**
- [.] Yes

**Description of Issue:**
When I click on install, it says "Extract: Bad Zip file"

**Steps to Reproduce:**
1. ```flatpak install flathub io.github.Foldex.AdwSteamGtk```
2. Open AdwSteamGtk
3. click Intsall

https://user-images.githubusercontent.com/94163435/210203724-2a555316-9e0b-4ee7-9dc4-db1dd3faa5f6.mp4

**Comment by Foldex** [comment]
Likely a bad/incomplete download, quick fix would be to delete `~/.var/app/io.github.Foldex.AdwSteamGtk/cache/AdwSteamInstaller/latest.zip` and let it redownload the release.

That error toast probably should just offer the user to do that.

**Comment by NeuHix** [comment]
Solved.
