### ISSUE TITLE
Feature Request: Support for Steam Flatpak

### ISSUE THREAD

**Issue by forteller** [Foldex/AdwSteamGtk#11]
Would be great if this beautiful theme also could work with Steam installed trough Flatpak. I don't know if that's possible, but here's hoping. Thanks! :)

**Comment by Foldex** [comment]
Steam Flatpak installs are already supported.

**Comment by forteller** [comment]
Huh, it doesn't work for me. Could it be because I first installed the theme when I had normal Steam installed, then installed Steam flatpak after installing the theme? But then I'd think that the theme would start working after updating it, but it did not. I can try to uninstall and reinstall AdwSteamGtk.

**Comment by Foldex** [comment]
>Could it be because I first installed the theme when I had normal Steam installed, then installed Steam flatpak after installing the theme?

Unlikely, as it will try to install to both paths so long as they exist.
Is the theme showing up in steam's interface settings?

**Comment by forteller** [comment]
OMG, I'm so sorry! I had totally forgotten I needed to switch the skin in the settings! Thanks, and sorry again!
