### ISSUE TITLE
Feature Request: Command-line for automatic install

### ISSUE THREAD

**Issue by RobOT05442309** [Foldex/AdwSteamGtk#13]
Hello,

First of all, thanks you for taking on your time to maintain this software. I would like to be able to update automatically the Adwaita theme for Steam using command-line.

I saw that you've already implement the `-c` option that fetch the archive but is there any possibility that you could also implement something like `-i`, `-u`, `--install` or `--update` this way a script can run something like:

```
/usr/bin/flatpak run io.github.Foldex.AdwSteamGtk -c -i
```

Do you think that you could implement such feature?

Edit 1: I forgot to mention that the `-i` command line need to respect the user choice in the app regarding full theme, button on right or left, etc.

Edit 2: Ideally (this is totally optional if it take too much time to implement) my previous request about the user choice settings could also be enhanced by letting the user eventually override those one by passing arguments and if none are given, then fallback to the default user choice set in the application.
The command line could look like:

```
/usr/bin/flatpak run io.github.Foldex.AdwSteamGtk -c -i -p "window:right-all;theme:full;qr:show"
```

Or something similar, or even pointing to a file (if you are using a file to remember settings) like:

```
/usr/bin/flatpak run io.github.Foldex.AdwSteamGtk -c -i -f "/path/to/file.conf"
```

This could also allow users to deploy quickly with different configuration, but like I said, this is optional, just a thought!

Thanks for your time.

**Comment by Foldex** [comment]
> I would like to be able to update automatically the Adwaita theme for Steam using command-line.
> Do you think that you could implement such feature?

It's a good suggestion, though I'd like to avoid going too heavy on the CLI aspect here.

I could see the simplified `-i` to install your last selection/ fallback to defaults, but `-p` pretty much is just implementing a cli wrapper inside a graphical wrapper around the existing cli installer. Kinda hard at that point to not simply say "Just use the upstream installer".

**Comment by Foldex** [comment]
Well, I relented. There you go.

**Comment by RobOT05442309** [comment]
Thanks you a lot for all this options you add and the time you take to make them available!
