### ISSUE TITLE
Bug Report: Where are the logs

### ISSUE THREAD

**Issue by palexdev** [Foldex/AdwSteamGtk#14]
**This issue is specific to AdwSteamGtk and not the upstream project:**
-  Yes

**Description of Issue:**
I don't know, it just fails with some vague message. Where are the logs?

**Steps to Reproduce:**
1. Install

**Comment by Foldex** [comment]
New release fixes the issue of the installer's output not displaying on CLI, and added a [Troubleshooting](https://github.com/Foldex/AdwSteamGtk/wiki/Troubleshooting) wiki page to explain some more common errors.

I don't know what vague error you're referring to, but if you could post it then it would help.

**Comment by palexdev** [comment]
Great, I'll try again and report back 👍🏻

**Comment by Foldex** [comment]
As a note: Flathub's built in publishing delay means it'll be a couple hours before the new release actually gets pushed.

**Comment by palexdev** [comment]
@Foldex 
So, for some strange reason the `skins` directory was owned by `root`
After correcting the ownership and permissions it worked

Thanks for your work!
