### ISSUE TITLE
Bug Report: Crash when applying color scheme

### ISSUE THREAD

**Issue by UltraBlackLinux** [Foldex/AdwSteamGtk#15]
**This issue is specific to AdwSteamGtk and not the upstream project:**

- [x] Yes

**I have checked the [Troubleshooting](https://github.com/Foldex/AdwSteamGtk/wiki/Troubleshooting) page**

- [x] Yes

**Description of Issue:**

This crashes when applying a color scheme. It does not matter which one, as it even crashes when just selecting Adwita

**Steps to Reproduce:**
Select a color scheme

**[CLI Output](https://github.com/Foldex/AdwSteamGtk/wiki/Troubleshooting#running-in-cli):**
```
$ G_MESSAGES_DEBUG=all adwaita-steam-gtk
...
(adwaita-steam-gtk:42264): Gtk-DEBUG: 17:15:26.357: Connecting to session manager
(adwaita-steam-gtk:42264): Gtk-DEBUG: 17:15:26.357: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(adwaita-steam-gtk:42264): Gtk-DEBUG: 17:15:26.358: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned
(adwaita-steam-gtk:42264): GLib-GIO-DEBUG: 17:15:26.361: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
(adwaita-steam-gtk:42264): Gdk-DEBUG: 17:15:28.667: [destroyed object]: error 6: surface was destroyed before its role object

Gdk-Message: 17:15:28.667: Error 71 (Protocol error) dispatching toWayland display.
```

**Comment by Foldex** [comment]
Just want to be clear on wording, when you say 'apply' you mean selecting the scheme from the dropdown, and not actually installing the theme correct?
If that's the case, sounds the same as: https://github.com/Foldex/AdwSteamGtk/issues/5

I'm still not able to recreate this though, and it seemed like it worked on a similar setup for them. 
So not sure if it was an issue with their environment or possibly a bug elsewhere.
Any further information on your environment? Judging from the command, is that the AUR build? Does this happen with any other program?

**Comment by UltraBlackLinux** [comment]
That's weird. Tried to recheck and the issue is gone. No idea how a reboot could be related to that in any way
