### ISSUE TITLE
Feature Request: Add options for the new headerbar button patches

### ISSUE THREAD

**Issue by tkashkin** [Foldex/AdwSteamGtk#18]
I've recently added a few [new patches](https://github.com/tkashkin/Adwaita-for-Steam/commit/5a64ac1c10801dda3323163b9a308da5875a0393) to the skin to show downloads or friends buttons (or both) in the headerbar.

It's a bit more complicated than other options because these patches are conflicting and currently only compatible with the default window controls preset. So for now this option should only be available/active when the window controls preset is set to default.

Not sure if there's a way to combine window controls presets with these patches without making each combination a separate patch. Maybe the installer should allow to add/remove/reorder headerbar buttons and modify `steamrootdialog.layout` directly.
Anyway, that's an issue for the skin itself, but maybe you'll have some ideas how to handle that.

**Comment by Foldex** [comment]
Honestly we might just consider ditching patches entirely. They're fairly fragile as we can't make changes to the affected areas as freely without also updating them in lockstep, and as you mentioned often conflict with themselves when multiple are involved.

I'd be fine delegating this to the installer. Off the top of my head a simple templating system, or even something like the current colortheme regex replacement would offer more control here.

This is something I had already considered regarding the windowcontrols patches, as with the dconf key `org.gnome.desktop.wm.preferences button-layout` you can already arbitrarily define window control items/order. But making patches for every single possible combination of those would be messy. In that particular case though, even with something more flexible we really only have control of the underlying layout for VGUI, for CSS we could handle reordering or hiding existing elements, but really can't add non-existing controls.

As for the new headerbar patches, not sure I'm a fan of currently including them if they're so limited with what they play nice with, especially if that includes themselves. With only two patches right now and the `all` patch, I guess it's not that big a problem, but adding anything past this will likely be an issue.

**Comment by Foldex** [comment]
Closing this, as the new UI invalidates these patches.
