### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by QazCetelic** [Foldex/AdwSteamGtk#2]
**This issue is specific to AdwSteamGtk and not the upstream project:**
- [x] Yes, I think so

**Description of Issue:**
Theme is not applied.

**Steps to Reproduce:**
1. Click Install
2. Open Steam

**Other Info (Shell Output, Screenshots, etc):**

**Installation**
![installation](https://user-images.githubusercontent.com/51381523/194900834-4c2e7191-7585-4dc1-89f3-9b721f6e3b89.png)

**Steam after installation**
![steam-screenshot](https://user-images.githubusercontent.com/51381523/194900969-f154e11b-e7a2-40ad-82d4-1f77ef2b148b.png)

**Comment by Foldex** [comment]
Couple of questions:
- What is the output when running from a terminal `flatpak run io.github.Foldex.AdwSteamGtk` and installing the skin?
- Does the skin show up in Steam's Interface Settings?
- Is this flatpak steam or from your normal package manager?

**Comment by Penglyn** [comment]
Same issue occured for me, but was solved by enabling Adwaita in the steam interface settings @QazCetelic

**Comment by QazCetelic** [comment]
I forgot to enable the theme in the steam interface settings.
