### ISSUE TITLE
Bug Report: latest version has broken light theme

### ISSUE THREAD

**Issue by cewbdex** [Foldex/AdwSteamGtk#20]
**This issue is specific to AdwSteamGtk and not the upstream project:**

- [x] Yes

**I have checked the [Troubleshooting](https://github.com/Foldex/AdwSteamGtk/wiki/Troubleshooting) page**

- [x] Yes

**Description of Issue:**

![obrazek](https://user-images.githubusercontent.com/9021297/232324318-bb173ccc-9f28-404f-bfa2-2a57784a645e.png)

**Steps to Reproduce:**
1. Launch

**[CLI Output](https://github.com/Foldex/AdwSteamGtk/wiki/Troubleshooting#running-in-cli):**
```
```

**Other Info (Screenshots, etc):**

**Comment by Foldex** [comment]
Should be fixed.
I've also added a preferences toggle for theme previews, in case users want to disable it.
