### ISSUE TITLE
Feature Request: List Cantarell font on description

### ISSUE THREAD

**Issue by tuconeves** [Foldex/AdwSteamGtk#21]
In some distros, the Adwaita theme on steam use a Serif font to show the texts due to the missing Cantarell Regular And Cantarell Bold fonts.
Installing the fonts to the system and restart Steam solve it.

Is it possible to list the font on the project readme and on Flathub?
[Link to the font download](https://www.1001fonts.com/cantarell-font.html)

Before:
![Before](https://user-images.githubusercontent.com/88161035/233782705-606ea9b8-4707-48e0-b798-0813c0634c4e.png)

After:
![Ater](https://user-images.githubusercontent.com/88161035/233783787-20a75968-0c52-4a36-88cf-96a350a3a1a2.png)

**Comment by Foldex** [comment]
Opened https://github.com/tkashkin/Adwaita-for-Steam/pull/141 upstream.
It'll have to wait till the next upstream release is made, but rather than pestering users about this we'll just add a preference to install it into a user owned font directory.
