### ISSUE TITLE
Bug Report: Steam removed skins in the new beta update

### ISSUE THREAD

**Issue by Sabering1** [Foldex/AdwSteamGtk#24]
Title

**Comment by Racsuu** [comment]
sadly if skins are not supported, and also the new ui is basically another thing to theme, this is not gonna be a thing anymore..

**Comment by Racsuu** [comment]
Pd:this a thing to discuss on steam forums, not here
https://steamcommunity.com/groups/SteamClientBeta/discussions/3/3826413850812597433/

**Comment by Sabering1** [comment]
well maybe something can be done to the steam ccs i dont know?

**Comment by Foldex** [comment]
See: https://github.com/tkashkin/Adwaita-for-Steam/issues/144

tl;dr
Skins are dead, but we can still patch steam client files.
We were already doing this to make library skinning work, so it's just a matter of porting the new ui over to this.
We have less control with the new UI though, so while most of the skin is doable, some loss of functionality is expected.
There's a very WIP beta branch [here](https://github.com/Foldex/Adwaita-for-Steam/tree/beta)

**Comment by Foldex** [comment]
Latest Release has Experimental Beta Support:
![image](https://github.com/Foldex/AdwSteamGtk/assets/47908676/56325d23-f726-4883-9753-b7e3cd09f3c2)


See https://github.com/Foldex/AdwSteamGtk/issues/25
