### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by Chrispycode** [Foldex/AdwSteamGtk#28]
**This issue is specific to AdwSteamGtk and not the upstream project:**

- [x] Yes

**I have checked the [Troubleshooting](https://github.com/Foldex/AdwSteamGtk/wiki/Troubleshooting) page**

- [x] Yes

**Description of Issue:**

Headerbar are not working, inspecting in dev mode also doesn't work

**Steps to Reproduce:**
1. Select Full Adwaita theme
3. enable custom css
4. paste this css
```
:root
{
	--bg: #eeeee;
	--fg: #FFFFFF;

	--accent: #C10022;
	--accent_bg: #6b0000;
	--accent_disabled: rgba(120, 0, 0, 0.5);
	--accent_hover_bg: rgba(120, 0, 0, 0.07);
	--accent_active_bg: rgba(120, 0, 0, 0.16);
	--focusring: #A83334;
	--button_bg: rgba(255, 0, 0, 0.1);
	--button_hover_bg: rgba(255, 0, 0, 0.15);
	--button_active_bg: rgba(255, 0, 0, 0.3);
	--button_disabled_bg: rgba(255, 0, 0, 0.05);
	--button_success_bg: linear-gradient(0deg, var(--success_bg), var(--success_bg));
	--button_suggested_bg: linear-gradient(0deg, var(--accent_bg), var(--accent_bg));
	--button_suggested_hover_bg: rgba(255, 0, 0, 0.1);
	--button_suggested_click_bg: rgba(0, 0, 0, 0.2);
	--checkbox_checked_bg: var(--button_suggested_bg);
	--checkbox_bg: transparent;
	--checkbox_active_bg: var(--button_active_bg);
	--radio_checked_bg: var(--button_fg);
	--card_bg: rgba(255, 0, 0, 0.1);
	--card_solid_bg: #eeeee;
	--entry_bg: var(--button_bg);
	--entry_hover_bg: var(--button_hover_bg);
	--window_bg: var(--bg);
	--view_bg: #eeeee;
	--headerbar_bg: #eeeee;
	--popover_bg: #eeeee;
	--toast_bg: rgba(0, 0, 0, 0.7);
}
```

**[CLI Output](https://github.com/Foldex/AdwSteamGtk/wiki/Troubleshooting#running-in-cli):**
```
patching file Adwaita/adw/controls/window.styles
Hunk #1 succeeded at 29 (offset -5 lines).
patching file Adwaita/resource/layout/steamrootdialog.layout
patching file Adwaita/resource/layout/uinavigatorpanel.layout
patching file Adwaita/resource/steamscheme.res
patching file Adwaita/steam/cached/UpdateNewsDialog.res
patching file Adwaita/resource/layout/htmlpopup.layout
patching file Adwaita/steam/cached/SingleUpdateNewsDialog.res
→ Copying to the stage directory /tmp/tmpti_84jqf/Adwaita

→ Applying patch windowcontrols/left...

→ Applying web_extra /home/chrispycode/.var/app/io.github.Foldex.AdwSteamGtk/config/AdwSteamGtk/custom...
→ Applying web_extra windowcontrols/left...


→ Applying web_extra /home/chrispycode/.var/app/io.github.Foldex.AdwSteamGtk/config/AdwSteamGtk/custom...
→ Applying web_extra windowcontrols/left...

✦ Directory /home/chrispycode/.var/app/com.valvesoftware.Steam/.steam/steam does not exist
→ Patching Steam Client Library Files...
✦ Directory /home/chrispycode/.var/app/com.valvesoftware.Steam/.steam/steam does not exist
→ Installing skin Adwaita into /home/chrispycode/.local/share/Steam/skins...
→ Patching Steam Client Library Files...
✓ Done!
```

**Other Info (Screenshots, etc):**
![image](https://github.com/Foldex/AdwSteamGtk/assets/22537998/57dd009f-610c-48a8-95db-ced48de42e28)

**Comment by Foldex** [comment]
> Headerbar are not working
Looks like you're using the Non-Beta Steam Client. This is expected, as it is written in VGUI and not CSS.
Custom CSS can only theme the headerbar for the Steam Client Beta, as they have gotten rid of VGUI.

See: [Here](https://github.com/Foldex/AdwSteamGtk/wiki/Custom-CSS#non-beta-client)

If you don't mind a more manual process and still want control over theming the stable client, you can follow: [This](https://github.com/Foldex/AdwSteamGtk/issues/22#issuecomment-1522595967)

I'm just not too personally interested in adding support for this to the app, as the VGUI client has its days numbered and I'm more focused on ironing out issues with the beta before it becomes stable.

I'll update the Troubleshooting page to make this more clear.

>inspecting in dev mode also doesn't work

Unclear if you meant the inspector doesnt work on the headerbar (expected), or if it doesn't work at all.
 
If the latter, sometimes `F12` doesn't seem to work. I've had better luck right clicking textboxes and selecting `Inspect Element`

**Comment by Chrispycode** [comment]
Ok thank you
