### ISSUE TITLE
Feature Request: Better localization readme

### ISSUE THREAD

**Issue by Vovkiv** [Foldex/AdwSteamGtk#30]
(Until weblate (or other platform) will be used for translations)
There high chance, that someone who want to contribute, never heard about ".po", ".pot" files, how to check their translation in-program or even don't know how to make pull request (or what is pull request is, fork). So, it's better to cover this users:
1. Add links to some po editors. Most popular would be https://flathub.org/uk/apps/net.poedit.Poedit
2. Add instructions on how to run program with newly added language. Since Builder is considered *official* build method, it worth showing how in it build program with new language.
3. Link some resources about forks, pull request and how to make them.
4. Some distros doesn't provide "gettext" utility. (for example, i'm on Fedora Silverblue and it doesn't have it out-of-box, maybe something like ubuntu or debian also doesn't) . So when user will run `/update_pot.sh` they might see "xgettext: command not found", so it's worth mention that to generate pot user need "gettext" package to actually do that (or, at least it's called in Fedora as such. Maybe on other distros it has different name, idk)

I'm writing this from perspective, that i myself learned how to do all of this stuff fairly recently and learning process itself was quite painful, since most devs don't even put any instructions. They already assume that you know all of this.

**Comment by Foldex** [comment]
Look good?

**Comment by Vovkiv** [comment]
Yes, it is much better now.
Tho, it MIGHT (or not) worth include something about countries codes (like this https://en.wikipedia.org/wiki/ISO_3166-1) or even full list of all available languages (like this one https://lingohub.com/developers/supported-locales/language-designators-with-regions) because, while there exist "ru" locale, there at least 5 variations of it by countries/republics/etc: ru-BY, ru-KG, ru-KZ, ru-RU, ru-TJ. And other languages also has them.

**Comment by Foldex** [comment]
Done, think we're good now.
