### ISSUE TITLE
Bug Report: No Custom themes for Steam anymore :sadge:

### ISSUE THREAD

**Issue by snoweuph** [Foldex/AdwSteamGtk#33]
Steam updated and theres no option for custom themes anymore, the new UI looks good and all, and better then the old default one, and sure it was time that it got an overhall, but why did they remove custom themes though :cry:

**Comment by Foldex** [comment]
While the skin system is gone, we are still able to theme the client via CSS patching.
AdwSteamGtk already supports the new UI via an opt-in preference (see #25).
This preference is no longer needed, so the next release will hit flathub in a few hours and just work on the new UI without it.
