### ISSUE TITLE
Top Bar Source Error

### ISSUE THREAD

**Issue by dinhokusanagi** [Foldex/AdwSteamGtk#35]
At the top there is a white burr up below the username (Dlnhc-Dinho) probably left from the source of the previous theme

![Captura de tela de 2023-06-17 19-22-00](https://github.com/Foldex/AdwSteamGtk/assets/43162113/e0d45793-53c6-45b1-a92a-77d6a5e77bd5)

**Comment by Foldex** [comment]
I tried to reproduce this, but wasn't able to. Neither the Stable nor the Beta version of Steam have this issue for me.
Not going to be able to do much further without more info.

In any case this is not the proper issue tracker. Issues for the skin itself go [here](https://github.com/tkashkin/Adwaita-for-Steam/issues).
Please recreate this issue there, and provide more info like if you are on the beta or not, and what options you used during the install.

**Comment by Foldex** [comment]
Update: Figured out what this was and PR opened upstream to fix this.
