### ISSUE TITLE
Weblate Integration

### ISSUE THREAD

**Issue by Foldex** [Foldex/AdwSteamGtk#36]
@Vovkiv @cmkohnen @AnaxMorden @RobOT05442309

Opening this just to clue in Translation Contributors.
I've been working on getting Weblate Integration set up.

You can see the project's Weblate page [here](https://hosted.weblate.org/projects/adwsteamgtk/adwsteamgtk/)
Currently it is in trial status, but I've sent in an application to have it granted free hosting. I don't foresee any issue with that going through, but I have locked contributions for the time being until it does.

Aside from that, I believe we should hopefully be good to go.
Bit of a PIA, but I've added detailed Labels and Screenshots for every applicable string I could.
If you want to give it an initial look over and provide any feedback you might have, feel free to do so.

**Comment by Vovkiv** [comment]
Looking good. Adding labels and screenshots really helps, especially with CLI stuff and toasts, that can be triggered with manually calling for errors. (Which is not always easy)

Days of manual po editing might come to end! (Tho, you should still leave how to contribute translation in old-fashioned way, just in case.)

**Comment by Foldex** [comment]
Weblate approved hosting the project, so I've opened up contributions.

**Comment by Vovkiv** [comment]
Finally!
