### ISSUE TITLE
Bug Report: Installer Process Failed

### ISSUE THREAD

**Issue by breningham** [Foldex/AdwSteamGtk#41]
**This issue is specific to AdwSteamGtk and not the upstream project:**

- [x] Yes

**I have checked the [Troubleshooting](https://github.com/Foldex/AdwSteamGtk/wiki/Troubleshooting) page**

- [x] Yes

**Description of Issue:**

Installation Process fails with the following output: 
```
usage: install.py [-h] [-c COLOR_THEME] [--custom-css] [-d]
                  [-e EXTRAS [EXTRAS ...]] [-l] [-t TARGET [TARGET ...]] [-u]

install.py: error: unrecognized arguments: -f
```

**Steps to Reproduce:**
1. Open ADWSteamGTK
2. Press "Apply"
3. Observe Message "Installer: Installer Process Failed"

**[CLI Output](https://github.com/Foldex/AdwSteamGtk/wiki/Troubleshooting#running-in-cli):**
```
♥ ❯ flatpak run io.github.Foldex.AdwSteamGtk 
usage: install.py [-h] [-c COLOR_THEME] [--custom-css] [-d]
                  [-e EXTRAS [EXTRAS ...]] [-l] [-t TARGET [TARGET ...]] [-u]
install.py: error: unrecognized arguments: -f
```

**Comment by nlogozzo** [comment]
Facing the same issue

**Comment by Foldex** [comment]
The font install option was recently removed from upstream, we no longer have to install fonts onto the system.
Next release should fix this.
For a short term fix, go into preferences and disable `Cantarell Fonts`.
