### ISSUE TITLE
Bug Report: Store recommendation window has no headbar

### ISSUE THREAD

**Issue by Bitals** [Foldex/AdwSteamGtk#48]
**This issue is a problem with AdwSteamGtk and not the [Theme](https://github.com/tkashkin/Adwaita-for-Steam) it installs:**

- [v] Yes

**I have checked the [Troubleshooting](https://github.com/Foldex/AdwSteamGtk/wiki/Troubleshooting) page**

- [v] Yes

**Description of Issue:**

Store recommendation window has no headbar, thus making it very hard to drag around.

**Steps to Reproduce:**
1. Launch Steam
2. Get a Recommendation window
3. Try to move it

**Other Info (Screenshots, etc):**
![image](https://github.com/Foldex/AdwSteamGtk/assets/11341915/5c7d2633-f725-4910-99b2-14b3f34768c3)

**Comment by Foldex** [comment]
This is a theme issue, not an issue with the installer.
