### ISSUE TITLE
Bug Report: Window hanging

### ISSUE THREAD

**Issue by Chaoscaot** [Foldex/AdwSteamGtk#5]
**This issue is specific to AdwSteamGtk and not the upstream project:**
- [x] Yes

**Description of Issue:**
The window is hung after selecting something in a dropdown menu.
It then can't be moved any more as well as any hover actions are not showing, clicking the dropdowns still works.
Clicking 'Install' directly installs the skin and doesn't hang the window.

**Steps to Reproduce:**
1. Click on one of the dropdowns in the window
2. Select something
3. Try to move the window or try clicking 'Install'

**Other Info (Shell Output, Screenshots, etc):**
- Fedora 36 with Gnome 42

**Comment by Foldex** [comment]
[test](https://user-images.githubusercontent.com/47908676/199623610-7d524c50-013f-4598-bde0-ab74bec05d91.webm)

Couldn't reproduce it on Arch or a Fedora VM.
Is there any console output when running via `flatpak run io.github.Foldex.AdwSteamGtk`?

**Comment by Chaoscaot** [comment]
Tried a little bit more with this,
On my Notebook, also running Fedora 36 with Gnome, it worked flawlessly. Also on my secondary monitor (3840x2160, primary: 2560x1440 144Hz).

[03.11.2022, 13:47:25.webm](https://user-images.githubusercontent.com/46247200/199724476-769680d9-5c98-4c38-bbce-8157a83a1ea5.webm)

Now it seems more like the bug is somewhere else, but I don't know where.
