### ISSUE TITLE
Help?: Can't find the button to add non-steam games or activate game keys "ADD A GAME"

### ISSUE THREAD

**Issue by mateowoetam** [Foldex/AdwSteamGtk#57]
## **This issue is a problem with AdwSteamGtk and not the Theme it installs:**

- [x ] It's an issue with the GUI choices but not the theme itself, so I guess yes?

## I have checked the Troubleshooting page

- [ x] Yes

## Description of Issue:

usually at the bottom left corner there is a button to add games (ADD A GAME button) , but when I installed this the button is no longer there, and I don't know how to find it, if it is somewhere else or if it just isn't in any place.

## Steps to Reproduce:
run AdwSteamGTK
install the theme
button no longer there, nor anywhere

## [CLI Output]:
not applicable, this is in regards to the GUI

### Normal Client with "ADD A GAME" button : 
![steamclient-399636535](https://github.com/Foldex/AdwSteamGtk/assets/79337611/745f24fd-adfe-4781-8787-70aa9707f730)

### Client with theme and no button:
![Screenshot_20240302_110644](https://github.com/Foldex/AdwSteamGtk/assets/79337611/3d5f2cab-1c54-4eac-82ce-b65c5d0fb3ce)

**Comment by Asriel115** [comment]
> ## **This issue is a problem with AdwSteamGtk and not the Theme it installs:**
> 
>     * [x ] It's an issue with the GUI choices but not the theme itself, so I guess yes?
> 
> 
> ## I have checked the Troubleshooting page
> 
>     * [ x] Yes
> 
> 
> ## Description of Issue:
> 
> usually at the bottom left corner there is a button to add games (ADD A GAME button) , but when I installed this the button is no longer there, and I don't know how to find it, if it is somewhere else or if it just isn't in any place.
> ## Steps to Reproduce:
> 
> run AdwSteamGTK install the theme button no longer there, nor anywhere
> ## [CLI Output]:
> 
> not applicable, this is in regards to the GUI
> ## Other Info (Screenshots, etc):
> ### Normal Client with "ADD A GAME" button :
> 
> ![steamclient-399636535](https://private-user-images.githubusercontent.com/79337611/309485825-745f24fd-adfe-4781-8787-70aa9707f730.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzQ4OTksIm5iZiI6MTcwOTY3NDU5OSwicGF0aCI6Ii83OTMzNzYxMS8zMDk0ODU4MjUtNzQ1ZjI0ZmQtYWRmZS00NzgxLTg3ODctNzBhYTk3MDdmNzMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDIxMzYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NjBiM2NjMzE2ZWMzNWIyMGYwMzI0MzlmNjhjZGZhNTIzOGE5MTFlNGY5OTg0N2E3YjIwNDZlZWM2M2ZhM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QJKTI0oQNGcNHotd7hVKRPXUk8znBeT0xXlIopX3ZcQ)
> ### Client with theme and no button:
> 
> ![Screenshot_20240302_110644](https://private-user-images.githubusercontent.com/79337611/309485874-3d5f2cab-1c54-4eac-82ce-b65c5d0fb3ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NzQ4OTksIm5iZiI6MTcwOTY3NDU5OSwicGF0aCI6Ii83OTMzNzYxMS8zMDk0ODU4NzQtM2Q1ZjJjYWItMWM1NC00ZWFjLTgyY2UtYjY1YzVkMGZiM2NlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDIxMzYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5Y2E1NDEwYzdjNmI1YzZjOGZlMjBmYmJlNGM1ZGUxZWUyNDJhNmUyOTg0M2VlMWY5ZmQyNjAyZjUzMzJiMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u7k4ys8HlxtHvJkCQWN12cyUtqzi8lGXuyn3f7ash6Y)

![Screenshot_20240305_163156](https://github.com/Foldex/AdwSteamGtk/assets/63687010/d9fbb752-ca0a-4583-a733-350a54042046)
I managed to get it from the settings under library

**Comment by mateowoetam** [comment]
thank you.
