### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by h-lavaei** [Foldex/AdwSteamGtk#61]
when steam has been installed with other package managers then flatpak it doesnt install themes correctly but its says it was successfu. (in my situation pacman)

here is the log : 

→ Creating stage directory /tmp/tmp59f7m4td/adwaita
→ Applying color theme breeze...

→ Patching Steam Client Library Files...
✦ Directory /home/hosein/.var/app/com.valvesoftware.Steam/.steam/steam does not exist
✓ Done!

as you can see /home/hosein/.var/app/com.valvesoftware.Steam/.steam/steam does not exists witch is path of steam that is installed with flatpak

**Comment by Foldex** [comment]
```
✦ Directory /home/hosein/.var/app/com.valvesoftware.Steam/.steam/steam does not exist
```
This is just an informational printout, not an error.
It tries to install to both the native steam and flatpak locations, you simply don't have the flatpak, so it doesn't install there.

If you are having an issue with the theme actually applying, and it only happens with AdwSteamGtk and not the upstream install script, feel free to reopen.
