### ISSUE TITLE
Adwaita-for-Steam v3.0: New window controls options

### ISSUE THREAD

**Issue by tkashkin** [Foldex/AdwSteamGtk#66]
v3.0 of the upstream skin is going to remove the remaining windowcontrols extras and replace them with new installer options:

* `--windowcontrols-theme` - currently supports `auto`, `adwaita`, `windows`, `macos`.
`auto` chooses the style depending on current platform.
* `--windowcontrols-layout` - `auto`, `gnome`/`adwaita`, `pantheon`/`elementary`, `windows`, `macos`, or custom GNOME-compatible button layout string.
`auto` will try to read `org.gnome.desktop.wm.preferences button-layout` on Linux.

I can keep the [upstream pull request](https://github.com/tkashkin/Adwaita-for-Steam/pull/281) open for a few days until AdwSteamGtk is updated.

**Comment by Foldex** [comment]
Have support for this now, with one caveat.
Can't quite seem to get the `button-layout` key to be read properly from within the flatpak sandbox.

It should in theory be getting transparently handled by the desktop portal, but can't seem to get it to return anything besides `appmenu:close`. 
The usual sandbox hole punching doesn't seem to be working for me either on this.

![image](https://github.com/user-attachments/assets/60cae989-a279-42de-8406-e22670690440)

**Comment by tkashkin** [comment]
Reading it through the desktop portal seems to work:
![image](https://github.com/user-attachments/assets/ce01da67-94eb-4ffd-a425-2c0702c4c871)

You should be able to read the button layout using libportal. Also GTK probably exposes button layout somewhere as well.

**Comment by Foldex** [comment]
Doh, of course. 
I had incorrectly assumed that just letting the script call gsettings might still work, but obviously can just grab it through the dbus portal. Thanks.

Should be good to go on this then.
