### ISSUE TITLE
Feature Request: create copr repo for fedora

### ISSUE THREAD

**Issue by CodedIsTaken** [Foldex/AdwSteamGtk#67]
Create a copr repo for fedora Linux.

**Comment by CodedIsTaken** [comment]
> I think for the forseeable future the only official build is going to be the flatpak. Individual distro packaging isn't something that I'm too interested in right now.

May I maintain the repo?

**Comment by Foldex** [comment]
If you're down for it then sure, my own personal interest is sort of irrelevant in that case :+1:

**Comment by CodedIsTaken** [comment]
> If you're down for it then sure, my own personal interest is sort of irrelevant in that case 👍

Oh, here's and update, you can ask the guys here to package it for you for fedora, ultramarine, nobara, etc. etc. without having to build it yourself. https://terra.fyralabs.com/

Get in touch with them however you can.

**Comment by deusnovus** [comment]
> Get in touch with them however you can.

He already told you he's not interested and you really need to stop incessantly demanding for a copr repo over and over. I've seen your same request word-for-word with the same annoying tone in tens of repos this past month. Asking developers to implement a feature only you are interested in takes away time from development; that's why the community maintains these without burdening the developer. You are free to maintain whatever package you want without asking, so if that's something you want to do yourself, by all means, go ahead.

**Comment by CodedIsTaken** [comment]
> > Get in touch with them however you can.
> 
> He already told you he's not interested and you really need to stop incessantly demanding for a copr repo over and over. I've seen your same request word-for-word with the same annoying tone in tens of repos this past month. Asking developers to implement a feature only you are interested in takes away time from development; that's why the community maintains these without burdening the developer. You are free to maintain whatever package you want without asking, so if that's something you want to do yourself, by all means, go ahead.

This isn't about a copr repo, this is about accessibility to users if they need this when they need it truly, not everyone can use a dang flatpak, I'm not even telling him to even open a copr repo I'm telling him to ask the Terra developers, I'm doing this for accessibility and allowing more people to access things and if you don't like it then simply block me

**Comment by CodedIsTaken** [comment]
> > > Get in touch with them however you can.
> > 
> > 
> > He already told you he's not interested and you really need to stop incessantly demanding for a copr repo over and over. I've seen your same request word-for-word with the same annoying tone in tens of repos this past month. Asking developers to implement a feature only you are interested in takes away time from development; that's why the community maintains these without burdening the developer. You are free to maintain whatever package you want without asking, so if that's something you want to do yourself, by all means, go ahead.
> 
> This isn't about a copr repo, this is about accessibility to users if they need this when they need it truly, not everyone can use a dang flatpak, I'm not even telling him to even open a copr repo I'm telling him to ask the Terra developers, I'm doing this for accessibility and allowing more people to access things and if you don't like it then simply block me

additionally, adding onto this, suggesting the package to be placed onto the Terra repo doesn't take time from development, the discussion has also changed, you where saying it for "get in touch with them however you can", I mean suggest the package and just leave, you don't understand that Terra is separate from copr and is maintained by the community and fyralabs who queue and take in suggestions and package your software, developers do not need to package it, you completely missed the mark.

**Comment by CodedIsTaken** [comment]
> > > > Get in touch with them however you can.
> > > 
> > > 
> > > He already told you he's not interested and you really need to stop incessantly demanding for a copr repo over and over. I've seen your same request word-for-word with the same annoying tone in tens of repos this past month. Asking developers to implement a feature only you are interested in takes away time from development; that's why the community maintains these without burdening the developer. You are free to maintain whatever package you want without asking, so if that's something you want to do yourself, by all means, go ahead.
> > 
> > 
> > This isn't about a copr repo, this is about accessibility to users if they need this when they need it truly, not everyone can use a dang flatpak, I'm not even telling him to even open a copr repo I'm telling him to ask the Terra developers, I'm doing this for accessibility and allowing more people to access things and if you don't like it then simply block me
> 
> additionally, adding onto this, suggesting the package to be placed onto the Terra repo doesn't take time from development, the discussion has also changed, you where saying it for "get in touch with them however you can", I mean suggest the package and just leave, you don't understand that Terra is separate from copr and is maintained by the community and fyralabs who queue and take in suggestions and package your software, developers do not need to package it, you completely missed the mark, not only because you were late to the discussion but you replied to the wrong comment.
