### ISSUE TITLE
Bug Report: Doesn't work on Debian 12 Bookworm new install

### ISSUE THREAD

**Issue by moanrial** [Foldex/AdwSteamGtk#70]
**This issue is a problem with AdwSteamGtk and not the [Theme](https://github.com/tkashkin/Adwaita-for-Steam) it installs:**

- [x] Yes

**I have checked the [Troubleshooting](https://github.com/Foldex/AdwSteamGtk/wiki/Troubleshooting) page**

- [x] Yes

**Description of Issue:**

When opening the flatpak version, there is no change in theme, or any new input. When opening with sudo -i flatpak run io.github.Foldex.AdwSteamGtk there is a symbolic link error and no theme applied.

X does not work.

**Steps to Reproduce:**
1. Open io.github.Foldex.AdwSteamGtk
2. Select Apply
3. ...... nothing

**[CLI Output](https://github.com/Foldex/AdwSteamGtk/wiki/Troubleshooting#running-in-cli):**
```
Traceback (most recent call last):
  File "/app/share/adwaita-steam-gtk/adwaita_steam_gtk/window.py", line 225, in install_theme
    (ret, msg) = install.run(options, self.beta_support)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/adwaita-steam-gtk/adwaita_steam_gtk/install.py", line 184, in run
    cmd = gen_cmd_line(options, beta_support)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/adwaita-steam-gtk/adwaita_steam_gtk/install.py", line 68, in gen_cmd_line
    button_layout = get_button_layout()
                    ^^^^^^^^^^^^^^^^^^^
  File "/app/share/adwaita-steam-gtk/adwaita_steam_gtk/install.py", line 160, in get_button_layout
    button_layout = portal.call_sync('org.freedesktop.portal.Settings.ReadOne', args, Gio.DBusCallFlags.NONE, -1, None)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Não existe o método “ReadOne” (19)


flatpak run io.github.Foldex.AdwSteamGtk
→ Copying to the stage directory /tmp/tmpybwucd5k/Adwaita


→ Applying web_extra login/hide_qr...
→ Applying web_extra library/hide_whats_new...

→ Installing skin Adwaita into /home/foldex/.var/app/com.valvesoftware.Steam/.local/share/Steam/skins...
✦ Directory /home/foldex/.steam/steam does not exist
```

**Other Info (Screenshots, etc):**
- ![imagem](https://github.com/user-attachments/assets/c82e5929-4d6a-4227-bc21-7a8bf5bae427)

**Comment by Foldex** [comment]
Looks like this is an issue with Debian having old software, as usual.
Their xdg-desktop-portal version doesn't seem to have the necessary method to read settings.

For a quick fix, change `Controls Button Layout` to `Adwaita` instead of `Auto`.
It won't perfectly match your system window control settings, but it should install the theme. 

We can still more gracefully handle dbus errors though, so I'll leave the issue open.
